name: Update README

on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_NEW }}
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.3'
      - name: Run update script
        run: go run update_readme.go
      - name: Commit and Push changes
        run: |
          git config --global user.name 'gilang swandaru'
          git config --global user.email 'gilangswandaru27@gmail.com'
          git add README.md
          git commit -m "Update README with greeting"
          git push
